/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harness/run-smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Smoke */
        post: operations["run_smoke_api_harness_run_smoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Intent Workflow */
        post: operations["run_intent_workflow_api_intent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Policy */
        post: operations["preview_policy_api_policies_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Policy */
        post: operations["parse_policy_api_policies_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Policy */
        post: operations["confirm_policy_api_policies_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/level-1-2/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Level 1 2 */
        post: operations["run_level_1_2_api_level_1_2_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Universe */
        post: operations["research_universe_api_research_universe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/analyst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyst Reports */
        post: operations["analyst_reports_api_research_analyst_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signal Board */
        post: operations["signal_board_api_signals_board_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/rebalance-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebalance Suggestions */
        post: operations["rebalance_suggestions_api_portfolio_rebalance_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/research-signal-daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Signal Daily Report */
        post: operations["research_signal_daily_report_api_reports_research_signal_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Signals */
        post: operations["run_signals_api_signals_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Portfolio Plan */
        post: operations["create_portfolio_plan_api_portfolio_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Order Plans */
        post: operations["create_order_plans_api_orders_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/generate-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Order Proposals */
        post: operations["generate_order_proposals_api_orders_generate_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/proposed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposed Orders */
        get: operations["proposed_orders_api_orders_proposed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Order */
        post: operations["approve_order_api_orders__order_plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_plan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Order */
        post: operations["reject_order_api_orders__order_plan_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_plan_id}/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modify Order */
        post: operations["modify_order_api_orders__order_plan_id__modify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_plan_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Order */
        post: operations["submit_order_api_orders__order_plan_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_plan_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Status */
        get: operations["order_status_api_orders__order_plan_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/guarded/run-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guarded Run Once */
        post: operations["guarded_run_once_api_autopilot_guarded_run_once_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/guarded/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Guarded */
        post: operations["pause_guarded_api_autopilot_guarded_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/guarded/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Guarded */
        post: operations["resume_guarded_api_autopilot_guarded_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Switch */
        post: operations["kill_switch_api_autopilot_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/kill-switch/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Kill Switch */
        post: operations["release_kill_switch_api_autopilot_kill_switch_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autopilot/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autopilot Status */
        get: operations["autopilot_status_api_autopilot_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/run-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Operator Run Once */
        post: operations["operator_run_once_api_operator_run_once_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operator Status */
        get: operations["operator_status_api_operator_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operator/reports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Operator Report */
        get: operations["latest_operator_report_api_operator_reports_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daily Report */
        post: operations["daily_report_api_reports_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutopilotPolicyRequest */
        AutopilotPolicyRequest: {
            /** Policy Id */
            policy_id?: string | null;
        };
        /**
         * BrokerMode
         * @enum {string}
         */
        BrokerMode: "mock" | "paper" | "live_disabled";
        /** ConfirmPolicyRequest */
        ConfirmPolicyRequest: {
            /** Policy Id */
            policy_id: string;
        };
        /** DailyReportRequest */
        DailyReportRequest: {
            /** Policy Id */
            policy_id?: string | null;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "backtest_only" | "paper_trading" | "approval_required" | "guarded_autopilot" | "fully_automated";
        /** FallbackDecision */
        FallbackDecision: {
            /**
             * From Level
             * @constant
             */
            from_level: 5;
            /**
             * To Level
             * @enum {integer}
             */
            to_level: 4 | 3 | 2 | 0;
            /** Reason Code */
            reason_code: string;
            /** Detail */
            detail: string;
            /**
             * Order Submission Enabled
             * @default false
             */
            order_submission_enabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Live Trading Enabled */
            live_trading_enabled: boolean;
            /** Default Broker */
            default_broker: string;
            /** Data Mode */
            data_mode: string;
            /** Data Mode Safe */
            data_mode_safe: boolean;
            /** Data Mode Error */
            data_mode_error?: string | null;
        };
        /** IntentRunRequest */
        IntentRunRequest: {
            /**
             * Text
             * @default KR stock moderate risk weekly rebalance, approval required, mock broker, limit orders only.
             */
            text: string;
            /**
             * User Id
             * @default fixture-user
             */
            user_id: string;
            /**
             * Create Order Proposals
             * @default true
             */
            create_order_proposals: boolean;
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /** Policy Id */
            policy_id?: string | null;
            /**
             * Reason
             * @default user_requested
             */
            reason: string;
        };
        /** Level12Request */
        Level12Request: {
            /** Policy Id */
            policy_id?: string | null;
            /**
             * Text
             * @default KR stock moderate risk weekly rebalance, approval required, mock broker, limit orders only.
             */
            text: string;
            /**
             * User Id
             * @default fixture-user
             */
            user_id: string;
        };
        /** ModifyOrderRequest */
        ModifyOrderRequest: {
            /** Quantity */
            quantity: number;
            /** Limit Price */
            limit_price?: number | null;
        };
        /** OperationReport */
        OperationReport: {
            /** Report Id */
            report_id?: string;
            /** User Id */
            user_id: string;
            /** Policy Id */
            policy_id: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Order Plan Ids */
            order_plan_ids?: string[];
            /** Fill Ids */
            fill_ids?: string[];
            /** Audit Event Count */
            audit_event_count: number;
            /**
             * Live Trading Enabled
             * @default false
             */
            live_trading_enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** OperatorDecision */
        OperatorDecision: {
            /** Decision Id */
            decision_id?: string;
            /** Run Id */
            run_id: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: number;
            /** Strategy Id */
            strategy_id?: string | null;
            /** Order Plan Id */
            order_plan_id?: string | null;
            /**
             * Action
             * @enum {string}
             */
            action: "submit" | "block" | "fallback" | "noop";
            /** Reason */
            reason: string;
            /** Risk Check Id */
            risk_check_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** OperatorReport */
        OperatorReport: {
            /** Report Id */
            report_id?: string;
            /** Run Id */
            run_id: string;
            /** User Id */
            user_id: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "blocked" | "fallback" | "failed";
            strategy_selection: components["schemas"]["StrategySelectionDecision"];
            /** Decisions */
            decisions: components["schemas"]["OperatorDecision"][];
            fallback?: components["schemas"]["FallbackDecision"] | null;
            /** Order Plan Ids */
            order_plan_ids?: string[];
            /** Broker Order Ids */
            broker_order_ids?: string[];
            /** Risk Check Ids */
            risk_check_ids?: string[];
            /** Safety Flags */
            safety_flags?: {
                [key: string]: boolean | string;
            };
            /**
             * Live Trading Enabled
             * @default false
             */
            live_trading_enabled: boolean;
            /**
             * Audit Event Count
             * @default 0
             */
            audit_event_count: number;
        };
        /** OperatorRunRequest */
        OperatorRunRequest: {
            /**
             * User Id
             * @default fixture-user
             */
            user_id: string;
            /** Policy Id */
            policy_id: string;
            /** Requested Policy Version */
            requested_policy_version: number;
            /**
             * Run Mode
             * @default dry_run
             * @enum {string}
             */
            run_mode: "dry_run" | "mock_submit" | "paper_submit";
            /**
             * Requested At
             * Format: date-time
             */
            requested_at?: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** OperatorRunResult */
        OperatorRunResult: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "blocked" | "fallback" | "failed";
            /** Submitted Order Plan Ids */
            submitted_order_plan_ids?: string[];
            /** Blocked Order Plan Ids */
            blocked_order_plan_ids?: string[];
            fallback?: components["schemas"]["FallbackDecision"] | null;
            report: components["schemas"]["OperatorReport"];
        };
        /** OrderIntent */
        OrderIntent: {
            /** Intent Id */
            intent_id?: string;
            /** Symbol */
            symbol: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** @default limit */
            order_type: components["schemas"]["OrderType"];
            /** Quantity */
            quantity: number;
            /** Limit Price */
            limit_price?: number | null;
            /** Notional */
            notional: number;
            /** Target Weight */
            target_weight: number;
            /** Reason */
            reason: string;
            /**
             * Quote Time
             * Format: date-time
             */
            quote_time?: string;
        };
        /** OrderPlan */
        OrderPlan: {
            /** Order Plan Id */
            order_plan_id?: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: number;
            intent: components["schemas"]["OrderIntent"];
            /** @default draft */
            status: components["schemas"]["OrderStatus"];
            /** Idempotency Key */
            idempotency_key: string;
            /** Risk Check Id */
            risk_check_id?: string | null;
            /** Risk Check Expires At */
            risk_check_expires_at?: string | null;
            explanation?: components["schemas"]["ProposalExplanation"] | null;
            /** Auto Order Reference Price */
            auto_order_reference_price?: number | null;
            /** Replaces Order Plan Id */
            replaces_order_plan_id?: string | null;
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** OrderPlanRequest */
        OrderPlanRequest: {
            /** Portfolio Plan Id */
            portfolio_plan_id?: string | null;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "draft" | "risk_checked" | "proposed" | "modified" | "user_approved" | "submitted" | "accepted" | "partially_filled" | "filled" | "cancelled" | "rejected" | "expired" | "failed";
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "limit" | "market";
        /** ParsePolicyRequest */
        ParsePolicyRequest: {
            /**
             * Text
             * @default KR stock moderate risk weekly rebalance, approval required, mock broker, limit orders only.
             */
            text: string;
            /**
             * User Id
             * @default fixture-user
             */
            user_id: string;
        };
        /** PortfolioPlan */
        PortfolioPlan: {
            /** Plan Id */
            plan_id?: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Version */
            policy_version: number;
            /** Target Weights */
            target_weights: {
                [key: string]: number;
            };
            /** Cash Target Weight */
            cash_target_weight: number;
            /** Order Intents */
            order_intents: components["schemas"]["OrderIntent"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** PortfolioPlanRequest */
        PortfolioPlanRequest: {
            /** Policy Id */
            policy_id?: string | null;
        };
        /** ProposalExplanation */
        ProposalExplanation: {
            /** Symbol */
            symbol: string;
            /**
             * Action
             * @enum {string}
             */
            action: "buy" | "sell";
            /** Quantity */
            quantity: number;
            /** Target Weight Delta */
            target_weight_delta: number;
            /** Reference Price */
            reference_price: number;
            /** Estimated Cash Impact */
            estimated_cash_impact: number;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Version */
            strategy_version: string;
            /** Signal Reason */
            signal_reason: string;
            /** Reason Codes */
            reason_codes?: string[];
            /** Current Weight */
            current_weight: number;
            /** Target Weight */
            target_weight: number;
            /** Weight Delta */
            weight_delta: number;
            /** Quote Price */
            quote_price: number;
            /** Quote Age Seconds */
            quote_age_seconds: number;
            /** Limit Price */
            limit_price?: number | null;
            /** Estimated Notional */
            estimated_notional: number;
            /**
             * Estimated Cost Bps
             * @default 0
             */
            estimated_cost_bps: number;
            /** Stop Price Hint */
            stop_price_hint?: number | null;
            /** Take Profit Hint */
            take_profit_hint?: number | null;
            /** Risk Checks Passed */
            risk_checks_passed?: string[];
            /** Risk Checks Failed */
            risk_checks_failed?: string[];
            /** Risk Check Id */
            risk_check_id?: string | null;
            /** Risk Check Expires At */
            risk_check_expires_at?: string | null;
            /** Idempotency Key */
            idempotency_key: string;
            /** Policy Version */
            policy_version: number;
            /** Warnings */
            warnings?: string[];
        };
        /** RejectOrderRequest */
        RejectOrderRequest: {
            /**
             * Reason
             * @default user_rejected
             */
            reason: string;
        };
        /** ReleaseKillSwitchRequest */
        ReleaseKillSwitchRequest: {
            /** Policy Id */
            policy_id?: string | null;
            /** Confirmation */
            confirmation: string;
        };
        /** Signal */
        Signal: {
            /** Signal Id */
            signal_id?: string;
            /** Strategy Id */
            strategy_id: string;
            /** Recipe Version */
            recipe_version: string;
            /** Symbol */
            symbol: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Signal Date
             * Format: date
             */
            signal_date?: string;
            action: components["schemas"]["SignalAction"];
            /**
             * Strength
             * @default 0
             */
            strength: number;
            /** Technical Score */
            technical_score?: number | null;
            /** Quant Score */
            quant_score?: number | null;
            /** Target Weight Hint */
            target_weight_hint?: number | null;
            /** Stop Price Hint */
            stop_price_hint?: number | null;
            /** Take Profit Hint */
            take_profit_hint?: number | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Policy Version */
            policy_version?: number | null;
            /** Reason Codes */
            reason_codes?: string[];
            /** Reason */
            reason: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Source
             * @default fixture_signal_stub
             */
            source: string;
        };
        /**
         * SignalAction
         * @enum {string}
         */
        SignalAction: "buy_ready" | "buy_wait" | "hold" | "trim" | "exit" | "watch" | "blocked";
        /** StrategySelectionDecision */
        StrategySelectionDecision: {
            /** Selected Strategy Id */
            selected_strategy_id: string | null;
            /** Selected Version */
            selected_version: string | null;
            /** Eligible Strategy Ids */
            eligible_strategy_ids: string[];
            /** Rejected */
            rejected: {
                [key: string]: string;
            };
            /** Reason */
            reason: string;
        };
        /** UserPolicy */
        UserPolicy: {
            /** Policy Id */
            policy_id?: string;
            /**
             * User Id
             * @default fixture-user
             */
            user_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Market
             * @default KR_STOCK
             */
            market: string;
            /**
             * Risk Profile
             * @default moderate
             */
            risk_profile: string;
            /**
             * Max Positions
             * @default 8
             */
            max_positions: number;
            /**
             * Max Position Weight
             * @default 0.15
             */
            max_position_weight: number;
            /**
             * Max Sector Weight
             * @default 0.4
             */
            max_sector_weight: number;
            /**
             * Min Cash Weight
             * @default 0.2
             */
            min_cash_weight: number;
            /**
             * Daily Loss Limit
             * @default -0.03
             */
            daily_loss_limit: number;
            /**
             * Monthly Loss Limit
             * @default -0.05
             */
            monthly_loss_limit: number;
            /**
             * Max Daily Orders
             * @default 3
             */
            max_daily_orders: number;
            /**
             * Max Daily Turnover
             * @default 3000000
             */
            max_daily_turnover: number;
            /**
             * Monthly Loss Pause New Buys
             * @default -0.05
             */
            monthly_loss_pause_new_buys: number;
            /**
             * Monthly Loss Stop All Autotrading
             * @default -0.1
             */
            monthly_loss_stop_all_autotrading: number;
            /**
             * Stale Quote Max Age Seconds
             * @default 30
             */
            stale_quote_max_age_seconds: number;
            /**
             * Human Review Quote Max Age Seconds
             * @default 120
             */
            human_review_quote_max_age_seconds: number;
            /**
             * Order Expiry Minutes
             * @default 30
             */
            order_expiry_minutes: number;
            /**
             * Authority Level
             * @default 2
             */
            authority_level: number;
            /**
             * Kill Switch Engaged
             * @default false
             */
            kill_switch_engaged: boolean;
            /**
             * Guarded Autopilot Enabled
             * @default false
             */
            guarded_autopilot_enabled: boolean;
            /**
             * Fully Automated Operator Enabled
             * @default false
             */
            fully_automated_operator_enabled: boolean;
            /**
             * Single Order Cash Limit
             * @default 1000000
             */
            single_order_cash_limit: number;
            /**
             * Rebalance Frequency
             * @default weekly
             */
            rebalance_frequency: string;
            /** @default approval_required */
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Allowed Order Types */
            allowed_order_types?: components["schemas"]["OrderType"][];
            /** @default mock */
            broker: components["schemas"]["BrokerMode"];
            /** Preferred Symbols */
            preferred_symbols?: string[];
            /** Preferred Themes */
            preferred_themes?: string[];
            /** Preferred Sectors */
            preferred_sectors?: string[];
            /** Blocklist */
            blocklist?: string[];
            /**
             * Min Avg Daily Value
             * @default 5000000
             */
            min_avg_daily_value: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_smoke_api_harness_run_smoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    run_intent_workflow_api_intent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_policy_api_policies_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParsePolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_policy_api_policies_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParsePolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_policy_api_policies_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_level_1_2_api_level_1_2_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_universe_api_research_universe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyst_reports_api_research_analyst_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_board_api_signals_board_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebalance_suggestions_api_portfolio_rebalance_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_signal_daily_report_api_reports_research_signal_daily_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Level12Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_signals_api_signals_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"][];
                };
            };
        };
    };
    create_portfolio_plan_api_portfolio_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_plans_api_orders_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_order_proposals_api_orders_generate_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposed_orders_api_orders_proposed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"][];
                };
            };
        };
    };
    approve_order_api_orders__order_plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_order_api_orders__order_plan_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modify_order_api_orders__order_plan_id__modify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_order_api_orders__order_plan_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    order_status_api_orders__order_plan_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guarded_run_once_api_autopilot_guarded_run_once_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutopilotPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_guarded_api_autopilot_guarded_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutopilotPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_guarded_api_autopilot_guarded_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutopilotPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_switch_api_autopilot_kill_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_kill_switch_api_autopilot_kill_switch_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseKillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autopilot_status_api_autopilot_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    operator_run_once_api_operator_run_once_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operator_status_api_operator_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    latest_operator_report_api_operator_reports_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    daily_report_api_reports_daily_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
